import React,{useEffect,useMemo,useState} from 'react'
import { useParams } from 'react-router-dom'
import { AlertTriangle,CheckCircle2,DatabaseZap,LibraryBig,ShieldCheck,XCircle } from 'lucide-react'
import { factoryService } from '../services'
import StatusPill from '../components/StatusPill'

export default function RunDetail(){
  const {runId}=useParams();const [run,setRun]=useState(null);const [audit,setAudit]=useState([]);const [tab,setTab]=useState('requirements');const [reviewer,setReviewer]=useState('GRC Reviewer');const [notes,setNotes]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('')
  const load=()=>Promise.all([factoryService.getRun(runId),factoryService.getAudit(runId)]).then(([r,a])=>{setRun(r);setAudit(a)}).catch(e=>setError(e.message))
  useEffect(()=>{load()},[runId])
  const pkg=run?.package;const controls=useMemo(()=>Object.fromEntries((pkg?.controls||[]).map(c=>[c.control_id,c])),[pkg]);const blockers=pkg?.qa_findings?.filter(f=>f.severity==='blocker')||[]
  async function review(decision){setBusy(true);setError('');try{await factoryService.review(runId,{reviewer,decision,notes});await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function publish(){setBusy(true);setError('');try{await factoryService.publish(runId);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  if(!run)return <div className="panel">{error||'Loading framework run…'}</div>
  return <div className="page-stack">
    <section className="run-hero"><div><div className="framework-monogram framework-monogram--large">{pkg?.metadata?.short_name?.slice(0,3)||'RUN'}</div><div><span className="panel__eyebrow">{pkg?.framework_key||run.run_id}</span><h2>{pkg?.metadata?.framework_name||'Framework run'}</h2><p>{pkg?.metadata?.country} · {pkg?.metadata?.regulator} · Version {pkg?.metadata?.version}</p></div></div><StatusPill status={run.status}/></section>
    {error&&<div className="alert alert--error">{error}</div>}
    <section className="run-stats"><div><strong>{pkg?.requirements?.length||0}</strong><span>Requirements</span></div><div><strong>{pkg?.mappings?.length||0}</strong><span>Mappings</span></div><div><strong>{pkg?.evidence_requirements?.length||0}</strong><span>Evidence requests</span></div><div><strong>{blockers.length}</strong><span>QA blockers</span></div></section>
    <div className="detail-grid"><section className="panel"><div className="tabs">{['requirements','mappings','evidence','qa','audit'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>
      {tab==='requirements'&&<div className="requirement-list">{pkg?.requirements?.map(r=>{const m=pkg.mappings.find(x=>x.requirement_id===r.requirement_id);return <article className="requirement-card" key={r.requirement_id}><div className="requirement-card__head"><span className="source-ref">{r.source_reference}</span><span className="domain-chip">{r.kind}</span></div><p className="source-quote">{r.source_text}</p><strong>{r.interpretation}</strong>{m&&<div className="mapping-inline"><span>{m.control_id}</span><b>{controls[m.control_id]?.title}</b><em>{Math.round(m.confidence*100)}%</em></div>}</article>})}</div>}
      {tab==='mappings'&&<div className="mapping-table">{pkg?.mappings?.map(m=><div className="mapping-row" key={m.mapping_id}><strong>{m.requirement_id}</strong><span>→</span><div><b>{m.control_id}</b><small>{controls[m.control_id]?.title}</small></div><em>{m.mapping_type.replaceAll('_',' ')} · {Math.round(m.confidence*100)}%</em><p>{m.rationale}</p></div>)}</div>}
      {tab==='evidence'&&<div className="evidence-grid">{pkg?.evidence_requirements?.map(e=><article className="evidence-card" key={e.evidence_id}><DatabaseZap size={18}/><div><span className="source-ref">{e.control_id}</span><h4>{e.title}</h4><p>{e.description}</p><div className="evidence-tags">{e.examples.map(x=><span key={x}>{x}</span>)}</div></div></article>)}</div>}
      {tab==='qa'&&<div className="qa-list">{pkg?.qa_findings?.length===0?<div className="quiet-state"><CheckCircle2/><strong>No QA findings</strong></div>:pkg.qa_findings.map(f=><div className={`qa-item qa-item--${f.severity}`} key={f.finding_id}>{f.severity==='blocker'?<XCircle/>:<AlertTriangle/>}<div><span>{f.code}</span><strong>{f.message}</strong></div></div>)}</div>}
      {tab==='audit'&&<div className="audit-list">{audit.map((a,i)=><div className="audit-event" key={i}><span/><div><strong>{a.event_type}</strong><small>{a.actor} · {new Date(a.created_at).toLocaleString()}</small><pre>{JSON.stringify(a.payload,null,2)}</pre></div></div>)}</div>}
    </section><aside className="panel review-panel"><div className="review-panel__head"><ShieldCheck/><div><span className="panel__eyebrow">HUMAN CONTROL</span><h3>GRC decision</h3></div></div><p>Review the complete source-backed package before changing its state.</p>{blockers.length>0&&<div className="decision-warning"><AlertTriangle size={16}/>{blockers.length} blocking finding(s). Approval is disabled.</div>}<label className="field"><span>Reviewer</span><input value={reviewer} onChange={e=>setReviewer(e.target.value)}/></label><label className="field"><span>Decision notes</span><textarea rows="5" value={notes} onChange={e=>setNotes(e.target.value)}/></label>{['awaiting_review','needs_rework'].includes(run.status)&&<div className="decision-actions"><button className="btn btn--danger" disabled={busy} onClick={()=>review('reject')}><XCircle size={16}/>Reject</button><button className="btn btn--primary" disabled={busy||blockers.length>0} onClick={()=>review('approve')}><CheckCircle2 size={16}/>Approve</button></div>}{run.status==='approved'&&<button className="btn btn--primary btn--full" disabled={busy} onClick={publish}><LibraryBig size={16}/>Publish package</button>}{run.status==='published'&&<div className="published-state"><CheckCircle2/><div><strong>Published</strong><span>Version locked.</span></div></div>}</aside></div>
  </div>
}
